### ISSUE TITLE
PFM transfer covering remote chain A's view of remote B's denoms

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10006]
## What is the Problem Being Solved?

Per @0xpatrickdev ,  we need and don't have any test scenarios for building PFM messages which require us to know RemoteChainA's view of RemoteChainB's denoms.

## Description of the Design

https://github.com/Agoric/agoric-sdk/pull/9491 made progress in pursuit of,
-  https://github.com/Agoric/agoric-sdk/issues/8863

However this is smaller in scope. The scope of this is testing PFM and the pfm memo. (Perhaps through sendAnywhere contract)

[Additional discussion](https://agoricopco.slack.com/archives/C06F5F867RB/p1718910779339949?thread_ts=1718057264.643829&cid=C06F5F867RB)

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/pull/10329
- [ ] implementation and test for COA
- [ ] https://github.com/Agoric/agoric-sdk/issues/10445
- [x] make variant of 10445 in which chain configs are read from JSON
- [ ] https://github.com/Agoric/agoric-sdk/pull/10584
```

**Comment by dckc** [comment]
A relevant detail: "chain A's view of remote B's denoms" is supposed to be called `getLocalDenom` as in `chainA.getLocalDenom(chainBdenom)`, according to July 31 discussion https://github.com/Agoric/agoric-sdk/pull/9814#discussion_r1699134254 where we dug up earlier API drafts.

A WIP version is included in
 - #9814

**Comment by 0xpatrickdev** [comment]
The remaining work is:
 - implementation and test for COA (`CosmosOrchestrationAccount`)

This will include a commit like https://github.com/Agoric/agoric-sdk/pull/10571/commits/c35fac7e82e6b66d2ffdc62ded1ba29a7d7388ff and ensuring tests continue to pass. It'd be nice if we included a test of a cosmos orch account performing a PFM transfer.

**Comment by dckc** [comment]
FastUSDC doesn't depend on multi-hop COA support, right?

Maybe split it out and close this?

**Comment by aj-agoric** [comment]
sirs @0xpatrickdev @turadg  requesting guidance on moving this to backlog

**Comment by turadg** [comment]
Since this was backlogged I'm dropping the P1 and my assignment.
