### ISSUE TITLE
e2e test env for FastUSDC

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#10184]
## What is the Problem Being Solved?

For **FastUSDC**, we need a testing environment that can be spun up locally and in CI. This environment should contain all of the necessary pieces to complete an E2E flow.

## Description of the Design

Where it makes sense, leverage the existing `multichain-testing` (starship) setup to integrate noble, cctp, and evm chain(s). Fully containerized services are preferably, but where the cost doesn't make sense we should connect to stable test networks.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10232
- [ ] https://github.com/Agoric/agoric-sdk/issues/10233
- [ ] https://github.com/Agoric/agoric-sdk/issues/10221
- [ ] https://github.com/Agoric/agoric-sdk/issues/10222
```

This task list will likely evolve over time, and should be broken out to separate issues.

**Comment by 0xpatrickdev** [comment]
All tasks are done with #10384
