### ISSUE TITLE
Fast USDC Core-Eval

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10301]
- [x] Start up FUC
- [x] Private invitations to become CCTP oracles (run by OCW)
- [x] Bootstrap test that
  - [x]  starts and
  - [x]  restarts it

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10386
- [ ] https://github.com/Agoric/agoric-sdk/pull/10478
```
