### ISSUE TITLE
complete FU Transaction Feed

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10457]
```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10387
- [x] transaction feed with access controls
- [x] transaction feed with aggregation logic
```
