### ISSUE TITLE
Perf measurement and profiling of FU w/SwingSet

### ISSUE THREAD

**Issue by LuqiPan** [Agoric/Agoric#10511]
## What is the Problem Being Solved?

"Fast" is in the name of the product. We should monitor performance of the system (especially the contract) throughout the project.

In particular, we should measure how many advancements we can do in a block; that is: how the computron cost of advancement compares to the block budget (currently 65Mc).

## Description of the Design / Test Plan

Expand swingset test tooling to support reporting computrons used. Use this tooling to measure cost of advancement.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/pull/10348
- [x] bootstrap test for advancement
- [ ] integrate computron counting in to bootstrap test for advancement
```

## Security Considerations

This task is mainly to confirm that performance is consistent with assumptions elsewhere in security modeling and design.

## Scaling Considerations

Mostly confirming that the system scales as expected.

## Upgrade Considerations

n/a/
