### ISSUE TITLE
Fast USDC transactions data source

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10598]
## What is the Problem Being Solved?

OpCo needs to be able to see the state of transactions.

Requires an indexing server

### Tasks
- [x] https://github.com/Agoric/agoric-sdk/issues/10578
- [x] https://github.com/Agoric/agoric-subql/issues/30
- [x] Fast USDC transaction indexing in opco-subql
- [x] https://github.com/Agoric/agoric-private/issues/244
