### ISSUE TITLE
rework EUD address hook to use bech32

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#10614]
## What is the Problem Being Solved?

https://github.com/Agoric/agoric-sdk/pull/10250 introduced address parameters. Not all chains we need to interop with support arbitrary address lengths.

## Description of the Design

Fit the data into a Bech32 address. 20 bytes for the Agoric address, 20 bytes for the EUD address.

~We'll need to enumerate the destination chains to fit into the 6 remaining bytes available.~ Now we have enough bytes

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/pull/10613
- [x] replace 'pfm' with an actual Noble ICA
- [x] use bech32 in FUSDC
```

**Comment by michaelfig** [comment]
More feedback from @dtribble is that we don't need to use the standard fixed-length (90-char) bech32, we can use a much larger limit (like 1000 characters) since there are already enough uses of larger bech32-formatted addresses across other chains in the Cosmos.

That should make this less work.

**Comment by dckc** [comment]
oops; I approved #10613 closing this, but there's more to it.

**Comment by dckc** [comment]
fixed in
 - #10682
