### ISSUE TITLE
make all proposals use `tryIstBalances` in `a3p-integration`

### ISSUE THREAD

**Issue by anilhelvaci** [Agoric/Agoric#10774]
## What is the Problem Being Solved?
The nature of how IST fees are charged presents a flakiness in `a3p-integartion`. See https://github.com/Agoric/agoric-sdk/issues/10565#issuecomment-2561923537. 

## Description of the Design
Iterate over all tests under `a3p-integration` and switch using `tryIstBalances` once a test doing otherwise is detected. Address tickets that are already caused by not using `tryIstBalances`.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/10565
- [x] [priceFeedUpdate.test.js/openMarginalVault](https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/n%3Aupgrade-next/priceFeedUpdate.test.js#L91)
- [x] [mintHolder-helpers.js](https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/p:upgrade-19/test-lib/mintHolder-helpers.js#L122)
```

### Open Questions
**Do the provisionPool address ever get charged IST execution fee?**
This important for us because;
https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/p%3Aupgrade-19/provisionPool.test.js#L107-L112

and

https://github.com/Agoric/agoric-sdk/blob/e06691f3bb13d315a4b557b4711c33cabc94979c/a3p-integration/proposals/p%3Aupgrade-19/provisionPool.test.js#L134-L139

## Security Considerations
None.

## Scaling Considerations
None.

## Test Plan
All tests should pass in CI.

## Upgrade Considerations
Effects current and future upgrades. New proposals should use `tryIstBalances` so an effort should be made when reviewing PRs to detect instances where this is not the case.

**Comment by anilhelvaci** [comment]
## Do the provisionPool address ever get charged IST execution fee?
On a second thought, as long as we don't send any SwingSet transactions from `provisionPoolAddress` I don't believe the `beans` will accrue. So I don't think there's anything to worry.
