### ISSUE TITLE
RUN-Protocol Planning Epic

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#3863]
# Tasks for RUN Protocol (Treasury) ((StablecoinMachine))

## CLEANUPS

* [x] Add vault state LIQUIDATING  (#3712)
 * [X] Get rid of liquidationSeat.  (#3773)
    * Proceeds can be added to the vaultSeat on liquidation
 * [x] Split AMM startup out of Treasury (#3019)
 * [ ] Accounting for currency flows in Treasury & AMM (#3792, #2851)
 * [x] Add a Pool to hold the ProtocolFee and distribute it appropriate (#2851)
 * [X] `vault.updateUIState()` should take new state as param (#3772)
 * [x] Clean up addition of collateral (#2877)
 * [x] Clean up after initialMargin dropped from VaultFactory (#4176)

## ConstantProduct update (#3791)

 * [x] Remove newSwap  (#3860)
 * [x] Upgrade from `multipoolAutoswap` to `constantProduct AMM` (#3861)
 * [x] Add governance to constantProductAMM (#3862)
 * [x] Collect fees from AMM (#4032)

## New Features

 * [ ] Enable Governance to add new collateral type (#3924)
 * [x] make vaults transferrable (#3864)
    * owner can request that the vault seat be wrapped in an invitation
 * [x] Governance-controllable RUN debt-limit per collateral type (#3501)
 * [x] Interest rate changes should affect existing vaults (#4182)
 * [ ] VaultFactory should start a vat per collateral type (#4184)
 * [x] Vault periods for charging interest and recording should be static (#4185)

## GOVERNANCE

 * [x] Next internal demo: AddCollateralType to the Treasury via governance (#3913)
 * [x] ContractGovernance for Treasury (#3310, in review, #3473)
 * [ ] make Choice of vaultContract pluggable (#3774)
 * [X] Add governance functionality for adding new collateral types (#3502)
 * [x] Add governance functionality for changing liquidation contract (#3865)
 * [ ] Create governance framework for electing a board  (#3866)
    * Visible candidates
    * Top-N candidates win seats
    * New registrar is visible and usable
    * Nomination mechanism
    * Stated duration terms with a possible referendum to hold new elections
    * Ranked choices, single transferable vote

 * [ ] Add multi-layer param governance (#3868)
   *  permitted param range is subject to change by super-majority

## SECURITY

 * [X] Write up security claims about VaultFactory (#4186)

**Comment by Chris-Hibbert** [comment]
There is some duplication with this [Treasury Running Task List](https://github.com/Agoric/dapp-token-economy/issues/101).

**Comment by dckc** [comment]
Is connecting the AMM to something that will extract the fees represented by an issue in this epic? Any existing issue? Or should I/we make a new one?

https://github.com/Agoric/agoric-sdk/blob/43b8eff0e428c69707e0325f9d6b9e56b014aaf2/packages/zoe/src/contracts/vpool-xyk-amm/multipoolMarketMaker.js#L132-L134

**Comment by Chris-Hibbert** [comment]
Good idea. I added an issue: #4032 and listed it up above, though it's not very specific yet.

**Comment by turadg** [comment]
Closing as this epic has served its purpose.
