### ISSUE TITLE
Rename RUN to Inter (IST)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/Agoric#5326]
https://github.com/Agoric/agoric-sdk/pull/5585 did most of this.

Left to do before closing Epic:

- [x] Documentation ticket filed https://github.com/Agoric/documentation/issues/689
- [x] ticket filed to deprecate [run-protocol package](https://www.npmjs.com/package/@agoric/run-protocol) is deprecated and points to inter https://github.com/Agoric/agoric-sdk/issues/5865
- [x] no results for `git grep "RUN [pP]rotocol" | grep -v CHANGELOG`

**Comment by zmanian** [comment]
If we could get this done soon, I can use the source code for communications about Inter

**Comment by Tartuffo** [comment]
@zmanian - @dckc has been working on this, he can advise as to the ETA.   We are going to change all of the strings that have the name 'RUN' in them (that get exposed in the UIs or contracts), but AFAIK we were not going to change the names of packages, directories, files, functions names, or in comments.

**Comment by Tartuffo** [comment]
@zmanian Unfortunately, we probably won't get to this until the first week in June.  Our engineers are working on preparing for both an economic stress test, and a security review.

**Comment by turadg** [comment]
#4800 was `Remove “BLD” and “RUN” from run-protocol code` but in epic here it says for string constants only, so that's what https://github.com/Agoric/agoric-sdk/pull/5585 does and not these bullets that were on the ticket:

1. Make them code parameters, which need names
2. “Central” applies to AMM hub-and-spoke
3. “feeMint” doesn’t make sense either
4. RUN is “stableMint” ? BLD is “collateralMint” ? 

Do we still need to do any of those?

@dckc does this epic capture everything that needs to be done? What about docs and `runStake` filenames?

**Comment by dckc** [comment]
I think #5585 covers the essential scope. (I'd say it _does_ cover 2, 3, and 4 above, but no matter.)

That said, I think renaming the runStake filenames to bldBoost is cost-effective at this point. I'm content for us to rename the internal identifiers later, if ever. I haven't reviewed the rest of the API surface, though. hm. Updating (producing?) docs for contract users is one of the better ways to review the situation.

**Comment by dckc** [comment]
Similar reasoning applies to renaming the package to `inter-protocol`, though I can imagine the cost might be sufficiently high that we should postpone it.

**Comment by dckc** [comment]
still todo: UI stuff, e.g. https://github.com/Agoric/dapp-treasury/issues/136

**Comment by ivanlei** [comment]
dapp-treasury has been archived. closing as done.
