### ISSUE TITLE
make vat-network upgradable

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#5696]
## What is the Problem Being Solved?

As part of #5666 we need to make the ["network vat"](https://github.com/Agoric/agoric-sdk/blob/1f2c46550f36530392eee449565c77858bbd4f18/packages/vats/src/vat-network.js) upgradable. This vat hosts a copy of 
[SwingSet/src/vats/network/router.js](https://github.com/Agoric/agoric-sdk/blob/1f2c46550f36530392eee449565c77858bbd4f18/packages/SwingSet/src/vats/network/router.js).

I'm not sure what this will entail (I'm not very familiar with this network code).

## Description of the Design

This includes not only making the network vat durable, but also providing a utility for clients of the network vat (such as Pegasus or ICA) to tolerate an upgrade (and its broken promises) without losing precious state.

## Test Plan

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/8906
- [ ] https://github.com/Agoric/agoric-sdk/pull/8721
- [ ] https://github.com/Agoric/agoric-sdk/issues/8950
- [ ] https://github.com/Agoric/agoric-sdk/pull/8948
- [ ] https://github.com/Agoric/agoric-sdk/issues/8867
```

**Comment by warner** [comment]
@gibson042 could you take a look at this and see how feasible it seems?

**Comment by warner** [comment]
@FUDCo walked through the `packages/SwingSet/src/vats/network/` code today.. we're thinking that maybe it should be moved out of swingset, either into `packages/vats/` that uses it, or into its own package.

His preliminary assessment is that making it upgradable wouldn't be too hard.

**Comment by Tartuffo** [comment]
@FUDCo making you the primary on this.

**Comment by FUDCo** [comment]
I spoke with @michaelfig and he said that moving this to `packages/vats` was reasonable, since it isn't really managed like the other vats that are part of SwingSet but is more of an IBC thing.  Apparently the primary reason this got put into `packages/SwingSet` was that `packages/vats` didn't exist at the time.

**Comment by warner** [comment]
break this into two pieces:
* reachably durable (#5973)
* known (tested) to be upgradable

We can defer the upgrade testing for after the `pso` milestone.

**Comment by dckc** [comment]
vat-network wasn't in the [pismo vats](https://github.com/Agoric/agoric-sdk/issues/5014#issuecomment-1309365804). I think it's only needed for dyanimc IBC, which isn't a vaults release feature

cc @warner @michaelfig
