### ISSUE TITLE
all vats that will be deployed in Vaults Release must be upgradable

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#6553]
## What is the Problem Being Solved?

Analogous to #5666:

> We need all of these to be upgradable, so we don't find ourselves stuck later when we want to add a feature or fix a bug. That means replacing their `Far` objects with instances of a durable `Kind`.

## Description of the Design

based on [a quick audit](https://github.com/Agoric/agoric-sdk/issues/5014#issuecomment-1309365804) it looks like the gaps are:

```[tasklist]
- [x] vat: zoe (#5283)
- [ ] https://github.com/Agoric/agoric-sdk/pull/6894
- [ ] https://github.com/Agoric/agoric-sdk/pull/6903
- [ ] https://github.com/Agoric/agoric-sdk/issues/7494
- [ ] https://github.com/Agoric/agoric-sdk/pull/7107
- [ ] https://github.com/Agoric/agoric-sdk/issues/7495
- [ ] https://github.com/Agoric/agoric-sdk/issues/5885
- [ ] https://github.com/Agoric/agoric-sdk/issues/4548
- [ ] https://github.com/Agoric/agoric-sdk/issues/7044
- [ ] https://github.com/Agoric/agoric-sdk/issues/7633
```

indicentally, not in pismoA nor vaults:
- https://github.com/Agoric/agoric-sdk/issues/5696

note related issues covering some startup vats/contracts not in the `@agoric/vats` package:
 - walletFactory #5894
 - zoe #4383
 - PSM (and presumably, psmCharter): #6099
 - governance #7248 
   - committee
   - contractGovernor
   - binaryVoteCounter

and there's perhaps some overlap in scope with #4511

## Security Considerations

_?_

## Test Plan

CI test (swingset or bootstrap) of each vat

cc @JimLarson @turadg @michaelfig @Chris-Hibbert

**Comment by dckc** [comment]
@Chris-Hibbert are the `committee`, `contractGovernor` and `binaryVoteCounter` contracts in the scope of #5200?

perhaps it's better to scope this to `packages/vats/`; #4983 covers `packages/inter-protocol`. #4511 isn't scoped to any package(s)... hm...

**Comment by Chris-Hibbert** [comment]
> are the committee, contractGovernor and binaryVoteCounter contracts in the scope of https://github.com/Agoric/agoric-sdk/issues/5200?

Yes.

**Comment by warner** [comment]
> That means replacing their Far objects with instances of a durable Kind.

To be picky (I was too glib in the issue that this line was copied from), it also requires:
* those KindHandles are kept in durable storage
* the startup process of each vat/contract uses Baggage and more `defineKind` calls to reassociate behavior with every Kind (`defineKind` must be called at the start of every incarnation, so once per upgrade)
* it also uses `provide` patterns to ensure that each exported *object* is only created once (in the first incarnation), not once-per-upgrade
* everything that behavior needs to do its job is kept in durable storage

But for sure, if you see `Far` in the code for a vat, and that object isn't explicitly marked as "subject to abandonment during upgrade, clients will observe the trauma and must be prepared to deal with it", then that vat is probably not really upgradable.

**Comment by dckc** [comment]
> ... it also requires: ...

Is that list collected anywhere for reference? Is https://github.com/Agoric/agoric-sdk/discussions/5708 still a good summary?

In any case, perhaps it's good input to https://github.com/Agoric/documentation/issues/750

**Comment by turadg** [comment]
@dckc I've replaced 5200 in the description with https://github.com/Agoric/agoric-sdk/issues/7248 which is about upgradability per se. That the state of governance is durable (#5200) is not strictly a requirement.

**Comment by turadg** [comment]
Treating this ticket as an epic, removing its estimate. Made each bare checklist item into an issue and estimated.

**Comment by dckc** [comment]
The last of the items on the checklist here is done:
 - #7633
