### ISSUE TITLE
Move UI components out of agoric-sdk

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6591]
## What is the Problem Being Solved?

UI development has different tooling and release requirements than the rest of agoric-sdk. https://github.com/Agoric/wallet-app/  was removed in https://github.com/Agoric/agoric-sdk/pull/6511

There remains `ui-components` and `web-components` which weren't moved at the time because they need tooling to publish to NPM. agoric-sdk has all that built in but moving them out will require setting that up in another repo.

Related issues: https://github.com/Agoric/agoric-sdk/issues/2320

## Description of the Design

Start a new repo for client code that is used in UIs. No changes could break anything server-side so it would have much faster testing.

Migrate these packages to it,
- `@agoric/ui-components`
- `@agoric/web-components`

does it include CLI as well as GUI?
- `@agoric/agoric-cli`

DECISION: no, that's too useful rn to agoric-sdk testing.

## Test Plan

New repo is https://github.com/Agoric/ui-kit 
```[tasklist]
### Tasks
- [x] new repo has CI running tests
- [x] new repo has CI running lint (eslint and types)
- [x] new repo has MAINTAINERS.md with how to publish to NPM
- [x] new repo has commit history for ui-components and web-components
```

**Comment by turadg** [comment]
For prioritization, example of PR bumping from merge queue due to flaky test for web-components:  https://github.com/Agoric/agoric-sdk/actions/runs/5216063114/jobs/9414454901
