### ISSUE TITLE
move atomicTransfer from helper into Zoe

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#6679]
## What is the Problem Being Solved?

#6577 added a new way to reallocate assets between Seats. In order to reduce the transition cost, the initial version was done as a helper method rather than building it into Zoe, and the previous approach (stagings) continues to be supported.

## Description of the Design

Remove the support for the old approach from Zoe, and move the implementation of the new approach into `ZCF`. `atomicRearrange` becomes a method on `ZCF`.

## Security Considerations

Better usability and robustness for developers. The only security implications are in the migration.

## Test Plan

#6577 didn't add tests. It instead relied on contract's usage to exercise the new API. We should add tests as we move it into Zoe.

## Action Steps

copying from a comment lower down so github can help with tracking:

The work involved includes
 * [x] adding new functionality to ZCF
 * [x] deprecating the old
 * [x] modifying all contracts in agoric-sdk
 * [x] updating contracts in other repos
and then later
 * [ ] removing the deprecated helper
```[tasklist]
### Tasks
```

**Comment by dckc** [comment]
Since #3850 is about the Zoe API and not about usage in some contracts, I re-opened it. I don't think it's worth tracking this separately; I suggest closing this as a dup.

**Comment by Chris-Hibbert** [comment]
#3850 is generic and has nothing specific to say about this approach, or how close it is to being finished. 

This issue is very focussed and indicates what work remains. It's the one I want to look at when I think about what to do next.

**Comment by dckc** [comment]
fair enough.

**Comment by Chris-Hibbert** [comment]
The work involved includes
 [x] adding new functionality to ZCF
 [x] deprecating the old
 [ ] modifying all contracts in agoric-sdk
 [ ] updating contracts in other repos
and then later
 [ ] removing the deprecated helper

**Comment by dckc** [comment]
> - modifying all contracts in agoric-sdk

Is there more of that to do? #6577 did a pretty thorough job of it, AFAICT.

**Comment by Chris-Hibbert** [comment]
> Is there more of that to do?

I don't know of anything that was missed, but the old methods are still there, so we can check before closing the issue.

**Comment by Chris-Hibbert** [comment]
#7900 added the functionality into ZCF.

**Comment by Chris-Hibbert** [comment]
I believe there are no remaining contracts in `agoric-sdk` that use `zcf.reallocate()`. I'm going to check that box.

There are still docs, comments and tests that refer to it. I will clean some of that up. When we remove the method from ZCF, we can get any that remains.

Is there any reason to believe there's any code in other repos (other than abandoned projects) that continues to use  `zcf.reallocate()`? Is there any third party code we should be concerned about?

**Comment by dckc** [comment]
I can't think of any relevant code that might be using it.

We could do an audit of mainnet bundles to be certain. It seems straightforward, if somewhat laborious.

**Comment by Chris-Hibbert** [comment]
There aren't very many contracts on MainNet (and fewer that do any allocation), so it shouldn't take long.

I've been thinking of  making a list of the versions of code in each vat. My main interest is tracking which version of ZCF got included in each contract as they upgraded, but it would also be helpful to track contract bundles.
