### ISSUE TITLE
stop reading denom purse balances from chainstorage 

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#6788]
## What is the Problem Being Solved?

A follow-on to https://github.com/Agoric/agoric-sdk/issues/6652 is to stop writing purse balances to chain storage. wallet-app and dapp-psm rely on this currently. This ticket serves to organize keeping that functionality working through the Vaults Release.

## Description of the Design

Basically read denom balances from Cosmos. The only purse that is read from chainstorage is Invitations.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/pull/6807
- [x] https://github.com/Agoric/wallet-app/issues/49
- [ ] https://github.com/Agoric/dapp-psm/issues/56
```

For the latter we could,
1. Make dapp-psm read denom balances from Cosmos
2. Make dapp-inter include PSM functionality (and  read denom balances from Cosmos)
3. Both

~We've chosen option #2 for Vaults release, meaning that dapp-psm will stop working and users will have to use the PSM part of dapp-inter. If we end up needing a separate dapp-psm we can make it.~

That was Jan 18. As of Jan 27 we opted for #1 instead because due to some other work that has landed #1 is cheaper than #2.
