### ISSUE TITLE
show all bids on liquidation auctions

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7159]
## What is the Problem Being Solved?

When bidding on liquidation auctions, a bidder may want to see not only their own bids but also the bids of others. (@rowgraus @btulloh care to elaborate on the motivation?)

## Description of the Design

The auctioneer contract has data structures for auction books. Make a **contract-api-change** to make them available to RPC queries via chainStorage.

Keep them up-to-date within some threshold. (_I think you suggested some specifics, @Chris-Hibbert . Do you recall?_)

Also add CLI support.

context: see also liquidation bidding CLI (#6930)

```[tasklist]
### Tasks
- [ ] #7905
- [ ] user can "npx @agoric/inter"
- [ ] #7906
- [ ] https://github.com/Agoric/agoric-sdk/issues/7952
- [ ] https://github.com/Agoric/agoric-sdk/issues/7953
- [ ] https://github.com/Agoric/agoric-sdk/issues/7954
- [ ] https://github.com/Agoric/agoric-sdk/issues/7955
- [ ] user help and documentation for bid list
- [ ] CI-validated documentation of vstorage for bid data consumers / tool builders
- [ ] functional CLI tests of "inter bid list" command
- [ ] proposal to shut down old auctioneer
```

## Security Considerations

_none that I can think of_

## Scaling Considerations

While in some sense, the number of outstanding bids could grow without bounds, practically it's likely to be manageable to publish them all.

## Test Plan

_IOU? much like other chainStorage tests in inter-protocol, I suppose_

**Comment by dckc** [comment]
### idea: return bid key in offer result

Currently, `agops inter bid list` gets its data from smart wallet RPC / vstorage / chainStorage info. The contract could also be enhance to emit bid info (such as IST remaining to fill). But I don't think there's any way to reliably join the two sources.

Meanwhile, the offer result from a successful bid is a string constant: **Your bid has been accepted**
Internally, the contract seems to generate a key for use in collections. If the offer result included that key in a parseable form, that would serve as a way to relate the collections.

### challenge: finding relevant wallet / address

The idea above solves the problem of: given data from a wallet and data from the contract, how do you join them? But if we want to start with just data from the contract and find relevant wallets (to find things like offer ids, tx ids, and timestamps) that's a whole other challenge.

cc @otoole-brendan

**Comment by dckc** [comment]
publishing a collection of bids reminds me of:

 - #7153
