### ISSUE TITLE
Vault creation grows heap

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#7297]
## What is the Problem Being Solved?

With https://github.com/Agoric/agoric-sdk/issues/7218 we learned that creating more vaults grows the heap. I.e. some objects are being retained through the vault creation that shouldn't be.

## Description of the Design

Find all the retaining paths and fix them. So far,

```[tasklist]
### Retention fixes
- [ ] https://github.com/Agoric/agoric-sdk/pull/7296
- [ ] https://github.com/Agoric/agoric-sdk/pull/7294
- [ ] https://github.com/Agoric/agoric-sdk/issues/7298
- [ ] https://github.com/Agoric/agoric-sdk/issues/7300
- [ ] https://github.com/Agoric/agoric-sdk/issues/7303
```

Then add regression tests (see Test Plan).

## Test Plan

We need a test that checks memory usage growth. This may be achievable by `process.memoryUsage()` comparison after vault runs. See https://github.com/Agoric/agoric-sdk/pull/7296#issuecomment-1492400754

**Comment by turadg** [comment]
Obsoleted with the sunsetting of Inter Protocol
