### ISSUE TITLE
test zoe null upgrade during running vaults system

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#7771]
## What is the Problem Being Solved?

Upgrading zoe in isolation is reasonably well tested, but I'm not aware that we've tested such an upgrade while the whole system is running. Do all the relevant parts survive the upgrade trauma?

## Test Plan / Design

 - [x] In the `docker-upgrade-test` context, make a core eval proposal to do a null upgrade of zoe.
 - [x] check that opening a vault still works
 - [ ] review logs and open issues for things such as seats that should have been garbage-collected but weren't exited (more: https://github.com/Agoric/agoric-sdk/issues/7771#issuecomment-1562009781)
 - [x] integrate this test into ci

## Security Considerations

Knowing that this works helps us understand our options should various risks arise.

## Scaling Considerations

none?

**Comment by dckc** [comment]
## Zoe null upgrade followed by create / adjust vault worked

@michaelfig and I got this to work

```
2023-05-18T17:02:31.717Z SwingSet: vat: v1: zoe upgrade: evaluating script                                                                                                                                                                   
2023-05-18T17:02:31.717Z SwingSet: vat: v1: restartZoe()                                                                                                                                                                                     
2023-05-18T17:02:31.717Z SwingSet: vat: v1: restartZoe - destructured powers                                                                                                                                                                 
2023-05-18T17:02:31.725Z SwingSet: vat: v1: restartZoe { bundleName: 'zoe', bundleCap: Object [Alleged: device node] {}, adminNode: Object [Alleged: adminNode] {} }                                                                         
2023-05-18T17:02:32.412Z SwingSet: kernel: vat v9 upgraded from incarnation 0 to 1 with source b1-af2a453c2bab9b08668704338b13c70edee2d6a5c162b1a34636f763c7ba206734752fe51ab3a598cbe8722465bf2ac5120c6a8aadc955251dbe5ca4d8fafb5c
```

### TODO: lights-out test

the PR has the files we used so far, but we didn't run it as part of the test framework

### Upgrade prompted diagnostics from vaultFactory, walletFactory

TODO: look at the diagnostics from v48, v43 in the logs below.

For reference, `ps` shows `v48:zcf-b1-d3a8b-vaultFactory`, `v43:zcf-b1-fb74c-walletFactory` 

### second run

```
cd deployment/upgrade-test
make build run
```

then in the container:

```
root@6596d2c41fa9:/usr/src/agoric-sdk# bash -x ./upgrade-test-scripts/agoric-upgrade-11/zoe-upgrade/zoe-upgrade-driver.sh 
... lots of output ...

root@6596d2c41fa9:/usr/src/agoric-sdk# agd --chain-id=agoriclocal query gov proposals --output json | \
        jq -c '.proposals[] | [.proposal_id,.voting_end_time,.status]';
["1","2023-05-18T15:53:17.082643401Z","PROPOSAL_STATUS_PASSED"]
["2","2023-05-18T15:57:49.143646670Z","PROPOSAL_STATUS_PASSED"]
["3","2023-05-18T15:59:00.152884368Z","PROPOSAL_STATUS_PASSED"]
["4","2023-05-18T17:52:40.151136900Z","PROPOSAL_STATUS_PASSED"]
```

[zoe-upgrade-log.txt](https://gist.github.com/dckc/0f702f12037a8a19c2bca9e85842b2c3#file-zoe-upgrade-log-txt)

**Comment by dckc** [comment]
log suggests something funky about `getPoserInvitation()` in `electorateTools.js` starting at 93

it's dropping the seat with `() => { ... }`. Possibly statically detectable?

if upgrading the zoe service caused the contract to exit a seat without failure, that's a bug in the zoe service, per @erights

**Comment by erights** [comment]
@dckc @Chris-Hibbert 
What's the status of the "upgrading the zoe service caused the contract to exit a seat without failure" question?

**Comment by dckc** [comment]
No news afaik

p.s. for follow-up, see:

 - https://github.com/Agoric/agoric-sdk/issues/7893
