### ISSUE TITLE
mainnet upgrade-12

### ISSUE THREAD

**Issue by warner** [Agoric/Agoric#7978]
## What is the Problem Being Solved?

Some time in the next month or two, we'll deploy a new version of Zoe and the ZCF bundle to our mainnet. This roughly consists of everything under `packages/zoe`. The deployment process involves two steps: first, the two bundles must be published to the chain (via a cosmos txn which does a `controller.validateAndInstallBundle()`), then a core-eval proposal must be approved by stakeholders and executed. @michaelfig 's deploy scripts perform both the bundle install and creates+submits the proposal, after which a vote can take place, and a YES vote will automatically trigger the core-eval. The core-eval will perform a `E(zoeVatAdminFacet).upgrade(newBundleCap)` to upgrade vat-zoe, and it will do some as-yet-unspecified interaction with zoe to make it use the new ZCF bundle (for new/upgraded contracts).

This ticket will track the code we intend to deploy in that upgrade, cross-module dependencies, etc. It is meant to fill the gap between "I got my PR landed, so development is done", and "my code has been deployed to our most important instance, the feature/bugfix/etc is now available to users". This should also provide a place to raise version dependencies between multiple deployable units which cannot all be deployed at the same time, e.g. "we're deploying ZCF v2, so new contracts and upgrades of existing contracts will start using it, but all existing/non-upgraded contracts will still keep using ZCF v1, so the Zoe v2 we just deployed must be compatible with both ZCF v1 and ZCF v2".

Note that any changes to files within the transitive dependency graph of those packages above will be incorporated into the deployment, whether they were deliberately intended for release or not. And many dependencies are shared by multiple deployable units. For example, a lot of Endo is imported by the kernel, but also by liveslots, and specific vats and contracts, all of which are deployed in separate actions, probably separated by weeks of time.

## Test Plan

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/7977
- [ ] https://github.com/Agoric/agoric-sdk/issues/7982
- [ ] https://github.com/Agoric/agoric-sdk/issues/8048
```
