### ISSUE TITLE
arbitrary well-known ERTP asset support in smart wallet

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8156]
## What is the Problem Being Solved?

The smart wallet supports vbank assets only (i.e. cosmos `x/bank` accounts reflected as ERTP purses); this suffices for the PSM and Vaults application, but not arbitrary ERTP assets as requested in #7226.

## Description of the Design

```[tasklist]
### Tasks
- [x] ["join game" use case](https://github.com/Agoric/agoric-sdk/issues/7226#issuecomment-1640483441) illustrates requirements
- [x] [failing test case](https://github.com/Agoric/agoric-sdk/pull/8071#issuecomment-1644926658)
- [x] [happy-path implementation](https://github.com/Agoric/agoric-sdk/pull/8071#issuecomment-1650924936)
- [x] how to handle `displayInfo`? (e.g. `decimalPlaces` but also `assetKind` to distinguish NFT from fungible)
- [x] watch already-stored purses; add `invitationPurse` to `brandToPurses` in `finish`?
- [ ] https://github.com/Agoric/agoric-sdk/pull/8120
- [x] upgrade walletFactory (incl. test)
- [x] publish displayInfo of all well-known brands under boardAux
```

## Security Considerations

Forgery risks around issuer/brand naming (#7226, #4819, #1449) are avoided by only supporting issuers from `agoricNames`.

## Scaling Considerations

n/a?

## Test /  Upgrade Considerations

noted in the design list above
