### ISSUE TITLE
test stATOM proposal in CI using an upgrade test

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8177]
## What is the Problem Being Solved?

The community's stATOM proposal will be tested elsewhere but we're not confident telling the community it's ready until the testing is automated.

Moreover, if we don't include it in the upgrade tests then they will drift from Mainnet. E.g. what is `vaultFactory.managers.manager1`

## Description of the Design

Add the proposal to a deployment upgrade test

The `addBrand` call should wait for the auction to complete. That signal comes from a subscriber, which should be careful to stop subscribing.

## Test Plan

Auctions continue to work for both. See also #8270 

## Upgrade Considerations

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/8235
- [ ] https://github.com/Agoric/agoric-sdk/issues/8347
- [ ] https://github.com/Agoric/agoric-3-proposals/pull/4
- [ ] https://github.com/Agoric/agoric-sdk/pull/8476
```

**Comment by dckc** [comment]
includes adding code to handle timing constraints to avoid #8296, #8307
per meeting with @turadg and co

> Without a fix, it's crucial that the oracle be started before the auction, and that the new brand is added to the auction after an auction round ends and before the next one starts.

**Comment by dckc** [comment]
fixed in https://github.com/Agoric/agoric-3-proposals/pull/4
