### ISSUE TITLE
upgrade-12 handler that includes zoe upgrade etc.

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8291]
## What is the Problem Being Solved?

We plan to upgrade walletFactory, zoe, etc. in upgrade 12. The currently tested mechanisms involve expensive `install-bundle` transactions followed by `core-eval` proposals. To save the expense, among other reasons, we plan to use one `software-upgrade` proposal, including all relevant core proposals, to do the upgrade.

## Description of the Design / Test Plan

Should #8219 be in scope here? Conservatively, let's say yes, for now...

```[tasklist]
### Tasks
- [ ] migrate walletFactory upgrade from a separate `core-eval` proposal to part of the `software-upgrade` proposal
- [ ] migrate the zoe and zcf upgrade likewise
- [ ] re-organize zoe and zcf upgrades in [`writeCoreProposals` style](https://github.com/Agoric/agoric-sdk/discussions/8087#discussioncomment-6534378), if not already done
- [ ] #8219
- [ ] https://github.com/Agoric/agoric-sdk/issues/8121
``` 

For reference:

#8112 introduced `--upgrade-info='{"coreProposals":[...]}'` and #8166 integrated it with docker upgrade-tests.

## Security / Scaling Considerations

not much

## Upgrade Considerations

yes. :)

**Comment by ivanlei** [comment]
This is no longer the plan of record.

**Comment by dckc** [comment]
let's close it as "not planned"

**Comment by dckc** [comment]
no longer the plan
