### ISSUE TITLE
smartWallet exits offers (e.g. bids) on zoe upgrade

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8292]
## Describe the bug

from the #8245 investigation with @warner:

when v9-zoe is upgraded, the wallet's `executeOffer()` code will observe the `E(seatRef).numWantsSatisfied()` promise get rejected/disconnected, which will reject the `tryBody()` promise, which will trigger the payment-recovery sequence and an `E(seatRef).tryExit()`, even though zoe's objects are still valid. Consequence: the offer is abandoned and refunded when that wasn't really necessary.

## Design / Plan

 - [x] capture the bug in a test
 - [x] diagnose
 - [x] fix on master, with durability
   - [ ] fix on #8488 branch
 - [ ] port fix to release branch (#8609)

## To Reproduce
1. place a bid
2. upgrade zoe
3. bid unexpectedly exits

## Expected behavior

Long-lived offers should survive upgrade of zoe.

## Platform Environment

mainnet1B

**Comment by dckc** [comment]
Since #8293 was [complicated by related work in progress](https://github.com/Agoric/agoric-sdk/issues/8293#issuecomment-1839052906), I got started on this on Friday, capturing the bug in a test:

2023-12-01 17:52 8eb9ccea6 WIP: test.failing('offer lasts across zoe upgrade',

I added a checklist to the description:

 - [x] capture the bug in a test
 - [x] diagnose
 - [x] fix on master, with durability
   - [ ] fix on #8488 branch
 - [ ] port fix to release branch by way of ([dev-upgrade-wallet-factory-2](https://github.com/Agoric/agoric-sdk/tree/dev-upgrade-wallet-factory-2)) branch introduced in #8593

**Comment by dckc** [comment]
I think recent work by @Chris-Hibbert addresses this.

**Comment by Chris-Hibbert** [comment]
#8445 fixes the issue. It's not yet on the release branch.

**Comment by aj-agoric** [comment]
Moving to done as @Chris-Hibbert  mentioned this was in the release branch and sufficiently tested.
