### ISSUE TITLE
walletFactory - migrate chain upgrade test to agoric-3-proposals

### ISSUE THREAD

**Issue by dckc** [Agoric/Agoric#8334]
## What is the Problem Being Solved?

code review in #8311 resulted in not only back-porting the walletFactory but also making some changes to it; for example:

 - using `instancePrivateArgs` rather than rebuilding the private args
 - reducing the scope/impact of the `fakeStorage.getBody()`

Meanwhile, there have been changes on master:

 - proposal builder stuff moved to the `builders` package to address cycles in our package dependencies
 - #8322

## Description of the Design

Originally: It's not clear how to address all these goals:

  - [x] we want the docker upgrade-tests to mirror mainnet and hence use the exact bundle from the backport
  - we want `local-chain` users to benefit from #8322 which fixed #8321
  - [x] we don't want to re-introduce cycles in our package dependencies

We came up with a design that addresses 2 of the 3:

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-3-proposals/pull/12
```

## Security Considerations

`instancePrivateArgs` is a pointy instrument. The choice of whether/how to use it is worth some consideration.

**Comment by dckc** [comment]
> ## Security Considerations
> `instancePrivateArgs` is a pointy instrument. The choice of whether/how to use it is worth some consideration.

 - #8378

**Comment by dckc** [comment]
We have this working in agoric-3-proposals:

 - https://github.com/Agoric/agoric-3-proposals/pull/12

I suppose I shouldn't close this until...

 - [ ] #8443

**Comment by dckc** [comment]
oops; accidentally closed it anyway

**Comment by dckc** [comment]
#8443 isn't critical path to the current consumer of this
