### ISSUE TITLE
Calypso - review of contract code (MN2 checklist)

### ISSUE THREAD

**Issue by aj-agoric** [Agoric/Agoric#8822]
Task: Code review the contract code which will be deployed to chain.

Purpose: Audit to raise confidence that contract implements desired behavior, is upgradable, properly uses durability & virtualization, doesn’t have bugs like infinite loops.

Instructions: OpCo engineers to arrange review with partner via Slack.

Description of the Design
 check timer watcher promises
 check vstorage collection structure
 check that any open issues are resolved
 check that sequence diagrams have corresponding tests
 check that work is limited by message size
```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9308
- [ ] https://github.com/Agoric/agoric-sdk/issues/9616
```

**Comment by dckc** [comment]
This contract is expected to deal in fungible amounts only, and therefore not trigger issues with large NFT amounts (#8862). Let's confirm during review.

**Comment by dckc** [comment]
The contract does _not_ return vows as offer results, does it?

If so, it depends on #9308

**Comment by Chris-Hibbert** [comment]
All I know is that there is vow code in it now, but that could be to handle vows from other sources cleanly.
@michaelfig  ?

**Comment by michaelfig** [comment]
> could be to handle vows from other sources cleanly.

Correct. The Calypso code currently interacts with the interaccounts contract (and, therefore, the network vat), which may return vows.

**Comment by dckc** [comment]
@michaelfig that sounds a little like a yes, the contract returns vows as offer results. I'm not quite sure that's what you're saying, but just in case it is, I marked this as blocked by #9308. Feel free to undo that if the contract's offer results are never vows.

**Comment by LuqiPan** [comment]
To paraphrase @dckc from Slack, sounds like there's a possible design that does NOT require a smart-wallet upgrade(i.e. #9308), it would be something that only required watched promises in the smart wallet.

Actionable item
- [ ] @michaelfig would need to talk to @erights about this possible design, created #9616 to track this task

~~(re-assigning this issue to @michaelfig and @erights)~~

**Comment by aj-agoric** [comment]
Confirmed this is needed prior to mainnet but not prior to orchnet demo launch for nebular

**Comment by aj-agoric** [comment]
Removing @dckc  as discussed, this will be picked but by perhaps him or someone in the near future
