### ISSUE TITLE
Convert awaits in network and ibc vats to promise watcher

### ISSUE THREAD

**Issue by iomekam** [Agoric/Agoric#8867]
## What is the Problem Being Solved?

We've been working on making the network and IBC vats durable (#8721). Leftover work from this initiative is that we haven't made promises durable yet, which prevents us from truly being able to upgrade.

## Description of the Design

As part of the `vow`(whenable) work, we've created promise watchers that are durable and can ensure that a promise is reconnected on upgrade. We need to go through the two vats and migrate any code awaiting on a Vow to use a watcher insead

open design questions:

 - [ ] use the vow-capable `E` work-alike?
 - [ ] convert _all_ awaits? or are there short-lived ones that should not be converted?

## Test Plan

 - [ ] upgrade / restart the vats at many points in the state machine

## Upgrade Considerations

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/8906
- [ ] #9027 
```

**Comment by dckc** [comment]
Following the [upgrade-at-each-point-in-a-flow test pattern](https://github.com/Agoric/agoric-sdk/blob/41d52be256b7a0f3e88af1e62b91667965a7dd26/packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js#L111), I'm trying to do some testing work to establish where the finish line is. I don't yet have a test failing in a way that shows that we're not already there. :-/

[test-net-ibc-upgrade.ts](https://github.com/Agoric/agoric-sdk/blob/dc-ibc-net-up-test/packages/boot/test/bootstrapTests/test-net-ibc-upgrade.ts) currently a06db4cb1, based on #8721

[net-ibc-test-log.md](https://gist.github.com/dckc/76d9a90a194aa9317f979983e620daf8#file-net-ibc-test-log-md)

cc @michaelfig @gibson042 @turadg

**Comment by dckc** [comment]
Richard found a failing test!

 - #8922
