### ISSUE TITLE
prepare updates for Upgrade 15

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/Agoric#8868]
## What is the Problem Being Solved?

A plan for the userland updates for Upgrade 15

## Steps (in order)

1.  **Zoe**
  * [x] Make a branch with #8682, #8697, #8497, #8498
  * [x] write the core eval #8915
  * [x] test #8682 in A3P. [#9010)
  * [x] test #8807 in A3P [#8911]
2.  **Price Feeds**. (see #8740)
  * [x] Add #8497 to branch
  * [x] replace #8498 with something that doesn't clean incrementally (#9013)
  * [x] add upgrading price feeds to core eval, see #8740.  (see #9044)
  * [x] test price feeds in A3P
3. **Auction**
  * [x] add #8691, #8438, #8301 to the branch
  * [x] add starting a new auction to the core eval. (#8918)
4.  **Vaults**
  * [x] add #8696, #8049, #8757  to the branch
  * [x] add upgrading Vaults to the core eval
  * [x] verify that upgrade succeeds (#8079)
  * [x] test #8788, #8789, #8293 in A3P

We decided (2/12) to upgrade from master rather than a branch, so it's not necessary to make branches. We still need the coreEvals.

**Comment by Chris-Hibbert** [comment]
@turadg  pointed out [the seat created in upgrade-10](https://github.com/Agoric/agoric-3-proposals/pull/31/files#diff-adfb14bc9f8ab997e556b5810a630ee869bbef87c76432477a4374a46261aed8) should still be live, and can be inspected to verify that the seat was fixed by 8682

**Comment by dckc** [comment]
I don't see #8123 in this plan. Is that on purpose?

@anilhelvaci Anil is doing some work on vault stuff and noticed that vaults do, in fact, lose the state of their governed parameters on upgrade.

**Comment by Chris-Hibbert** [comment]
> I don't see https://github.com/Agoric/agoric-sdk/issues/8123 in this plan. Is that on purpose?

Yes.
It was never included in lists of goals that I saw. AIR, We explicitly decided to deal with the consequences of non-persistent governance.

**Comment by dckc** [comment]
> We decided (2/12) to upgrade from master rather than a branch ...

That's now reified as:

 - https://github.com/Agoric/agoric-sdk/issues/9252

perhaps that should go in the task list here?

**Comment by Chris-Hibbert** [comment]
Last I heard, we were not planning to do any of the actually planned upgrades from master, but getting there is somewhere between a goal and a pious hope. I'm pretty sure something called upgrade 15 will go out without being pulled direct from master.

I think the things on this list are closer to upgrade 17 at this point, and so it's possible we'll include @9252, but I wouldn't consider it gating.
