### ISSUE TITLE
acceptance testing of Core-Evals to start vat and upgrade vats for Calypso

### ISSUE THREAD

**Issue by turadg** [Agoric/Agoric#8903]
## What is the Problem Being Solved?

- Calypso and Orc API both depend on the same vats
- The image below is a capture of components - vat/contracts or golang modules - critical for Calypso & Orchestration
- Everything in green in the image needs to be launched on chain before Calypso or Orc API

![image](https://github.com/Agoric/agoric-sdk/assets/21505/2d8313ec-be9a-436c-b5f7-f2bca5af2754)

This is related to https://github.com/Agoric/agoric-sdk/issues/8895 but this issue is part of delivery for the Calypso project and may have slightly different requirements.

## Description of the Design

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/5696
- [ ] https://github.com/Agoric/agoric-sdk/issues/8854
- [ ] https://github.com/Agoric/agoric-sdk/issues/8319
- [ ] https://github.com/Agoric/agoric-sdk/pull/8624
- [ ] https://github.com/Agoric/agoric-sdk/issues/8583
``` 

## Test Plan

A3P test of adding them all to the chain, as part of Upgrade 16

**Comment by schnetzlerjoe** [comment]
Everything in green believe is integrated in v16 upgrade. It is what we need to launch Calypso. So think this is complete. At least from my eyes.
