### ISSUE TITLE
Release steps can be improved

### ISSUE THREAD

**Issue by gibson042** [Agoric/Agoric#9079]
In following [MAINTAINERS.md](https://github.com/Agoric/agoric-sdk/blob/master/MAINTAINERS.md) to produce [release agoric-upgrade-14-rc1](https://github.com/Agoric/agoric-sdk/releases/tag/agoric-upgrade-14-rc1), I observed some opportunities for improvement:
- [x] [#9080] MAINTAINERS.md could be better-formatted, particularly in not breaking list formatting with non-indented content.
- [x] [#9080] It could also provide more guidance on how to check on publication of the expected Docker image.
- [ ] Speaking of which, the pre-release Docker image gets [published with a "latest" tag](https://github.com/Agoric/agoric-sdk/blob/7ba058ab6142e26fb3ca1bfd31a0a9756735ac17/.github/workflows/docker.yml#L166-L168)... is that really what we want?
- [x] [#9241] The "_Create a GitHub release_" step should probably have an actual (and possibly automated) template rather than instructions to use previous releases.
- [ ] The "_Check the development history oriented release description into the top-level CHANGELOG.md on the base branch_" step appears to not have been followed in a while—we should revisit what we actually want here.
- [x] [#9080] Generated tags should all be created in one step, rather than hiding creation of the `v…` tag inside a [get-released-tags](https://github.com/Agoric/agoric-sdk/blob/master/scripts/get-released-tags) script that _seems_ to be locally read-only but is actually not.
- [x] [#9080] [npm-dist-tag.sh](https://github.com/Agoric/agoric-sdk/blob/master/scripts/npm-dist-tag.sh) does a lot, especially in `lerna` mode, and should support dry-run.
- [x] [#9658] It also has way too many `npm login` prompts, and should be updated to behave more like `yarn lerna publish --concurrency 1 from-package` (which only prompted me once).

**Comment by gibson042** [comment]
This is pretty much done; anything further merits its own issue.
