### ISSUE TITLE
enhance smart wallet behavior when invitation creation fails

### ISSUE THREAD

**Issue by raphdev** [Agoric/Agoric#9239]
## What is the Problem Being Solved?

Currently smart-wallet lacks tests for failure to create invitation. This is a failure we want to handle to ensure we're handling invitations correctly in the smart wallet.

## Test Plan

Have test coverage for more edge cases.

## Upgrade Considerations

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/dapp-offer-up/pull/76
- [ ] https://github.com/Agoric/agoric-sdk/pull/9250
- [ ] https://github.com/Agoric/agoric-sdk/pull/9254
- [ ] https://github.com/Agoric/agoric-sdk/pull/9204
- [ ] https://github.com/Agoric/agoric-sdk/pull/9240
- [ ] https://github.com/Agoric/agoric-sdk/pull/9236
- [ ] https://github.com/Agoric/agoric-sdk/pull/9238
```
