### ISSUE TITLE
Integrate asyncFlow with orchestration API (umbrella issue)

### ISSUE THREAD

**Issue by raphdev** [Agoric/Agoric#9281]
`asyncFlow` itself is a low-level helper. For smooth integration with orchestration API, we'll need additional wrappers and helper functions to use with exos and allow injecting closed-over state in the membrane used by asyncflow. We'll also need to address hazards and current incompatibilities. 

This task captures details needed for integration and will detail learnings as we scope them.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9304
- [ ] https://github.com/Agoric/agoric-sdk/issues/9301
- [ ] https://github.com/Agoric/agoric-sdk/issues/9449
```

**Comment by 0xpatrickdev** [comment]
Added a task item: **Vows support in Orchestration Service (`makeAccount`, `executeEncodedTx`)**. 

Context:

[OrchestrationService](https://github.com/Agoric/agoric-sdk/blob/ae20e079e32df42628225404c4bf01edd9019c18/packages/orchestration/src/service.js) consumes Vows from `vat-network` and `vat-ibc` but does not produce them. It seems we may need to ensure certain lower level functions like `.makeAccount()`, `.query()`, and `.executeEncodedTx()` return Vows to support `asyncFlow` efforts. An open question seems to be whether things like [chainAccountKit.js](https://github.com/Agoric/agoric-sdk/blob/ae20e079e32df42628225404c4bf01edd9019c18/packages/orchestration/src/exos/stakingAccountKit.js) and [stakingAccountKit.js](https://github.com/Agoric/agoric-sdk/blob/ae20e079e32df42628225404c4bf01edd9019c18/packages/orchestration/src/exos/stakingAccountKit.js) will be implemented with asyncFlows or promise watchers / Vows.

**Comment by mhofman** [comment]
To clarify the async-flow requirements, the whole chain up to the orchestration helpers running in the vat using async-flow needs to be upgradable. For other vats that means using and consuming vows. For the vat using async-flow, that means the host API (the orchestration helper and other context or arguments objects) need to return vows (and not promises for vows)

**Comment by mhofman** [comment]
@mitdralla to sync up with Orchestration folks to see if anything else is missing in async-flow to fully enable orchestration MVP features.
