### ISSUE TITLE
Incomplete jsdocs for Orchestration API types, variables, methods and parameters

### ISSUE THREAD

**Issue by toliaqat** [Agoric/Agoric#9757]
## What is the Problem Being Solved?
The current [@agoric/orchestration](https://agoric-sdk.pages.dev/modules/_agoric_orchestration) reference docs (JSDocs)  are incomplete for the purpose of devrel to write stuff in docs.agoric.com.

Several methods and parameters are missing detailed descriptions, which hinders the ability of developers to understand and utilize the API effectively. 

The missing Orch API JSDocs can be tracked on...

 - [Orch API JSDoc Tracking](https://docs.google.com/spreadsheets/d/1aOuBx5CO6sq0fLZKDv2EE0p967SP32aAAV9mpkBO-YU/edit?gid=0#gid=0)

###  Expected Behavior:
The JSDocs should provide comprehensive information for all methods, including:

- A clear and concise description of each type, method, and variable.
- Detailed information on each parameter (name, type, description).
- Return type and description.
- Examples demonstrating how to use the API.

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9765
- [ ] https://github.com/Agoric/agoric-sdk/issues/9766
- [ ] https://github.com/Agoric/agoric-sdk/issues/9992
- [ ] https://github.com/Agoric/agoric-sdk/issues/9994
- [ ] exos/README.md needs to be refreshed and reviewed before NPM release
```

**Comment by dckc** [comment]
re inline `KnownChains` making `Orchestrator` messy:

 - https://github.com/TypeStrong/typedoc/issues/2273

**Comment by dckc** [comment]
Why is `connectionInfo: IBCConnectionInfo` referring to the type by name as expected but type for `chainInfo` is expanded???

![image](https://github.com/user-attachments/assets/2d16e41f-efbc-422a-883f-5c7fc2acc85a)

**Comment by dckc** [comment]
[OrchestrationFlow](https://agoric-sdk.pages.dev/interfaces/_agoric_orchestration.OrchestrationFlow) has no prose, but there's an Orchestration Flows blurb on the [@agoric/orchestration](https://agoric-sdk.pages.dev/modules/_agoric_orchestration.html) page. That blurb should probably move.

**Comment by dckc** [comment]
`GuestOf` could really use an example; in Office Hours, we started drafting one:

modified   packages/async-flow/src/types.d.ts
```diff
@@ -39,6 +39,12 @@ export type HostAsyncFuncWrapper = (
  * The function from the host as it will be available in the guest.
  *
  * Specifically, Vow return values are converted to Promises.
+ *
+ * @example
+ * const localTransfer = (...) => { return asVow(() => ...); };
+ * @param {GuestOf<ZoeTools['localTransfer']>} ctx.localTransfer
+ *
+ * from `orchestration/src/examples/sendAnywhere.flows.js`
  */
 export type GuestOf<F extends HostAsyncFuncWrapper> = F extend
```

**Comment by dckc** [comment]
Documentation of failure modes would be nice.

**Comment by dckc** [comment]
Functions / methods whose results await actions from other chains should be flagged.

In general, anything with cost > O(1) amortized should be documented.

**Comment by dckc** [comment]
@0xpatrickdev in **Documentation Considerations** of #10211, you write...
> These tests serve as documentation for using the `Deposit`, `Withdraw`, `Transfer`, and `Proxying` invitationMakers from the Orchestration API

Do we have any JSDoc for those? I'm struggling to find `PortfolioHolderKit` at all in [@agoric/orchestration](https://agoric-sdk.pages.dev/modules/_agoric_orchestration) API docs.

**Comment by 0xpatrickdev** [comment]
> @0xpatrickdev in **Documentation Considerations** of #10211, you write...
> 
> > These tests serve as documentation for using the `Deposit`, `Withdraw`, `Transfer`, and `Proxying` invitationMakers from the Orchestration API
> 
> Do we have any JSDoc for those? I'm struggling to find `PortfolioHolderKit` at all in [@agoric/orchestration](https://agoric-sdk.pages.dev/modules/_agoric_orchestration) API docs.

Good question, PR'ed here: https://github.com/Agoric/agoric-sdk/pull/10217
