### ISSUE TITLE
unbondExample.contract.js is incomplete

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/Agoric#9782]
## What is the Problem Being Solved?

[unbondExample.contract.js](https://github.com/Agoric/agoric-sdk/blob/8a8fed33ee6e578227775ed5ad9297f7336fb4be/packages/orchestration/src/examples/unbondExample.contract.js) currently has a lot of TODOs and incomplete functionality, but is documented on our docs site: https://docs.agoric.com/guides/orchestration/getting-started/contract-walkthrough/cross-chain-unbond.html

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9796
- [ ] https://github.com/Agoric/agoric-sdk/issues/10016
- [ ] https://github.com/Agoric/agoric-sdk/issues/10017
```

**Comment by amessbee** [comment]
@0xpatrickdev let me know if you want us to change anything in the docs.
